// MAX backend as a Cloudflare Worker.
//   - Static frontend: served by Workers Static Assets (see wrangler.jsonc). This Worker only runs for /api/*.
//   - Secrets (never in client code):  ANTHROPIC_API_KEY  (or another provider key)  ·  ADMIN_TOKEN  ·  MAX_SHARED_SECRET
//   - Optional KV binding MAX_KV: durable daily rate limits + admin override of the shared event.
//     Without it everything still works (limits fall back to per-isolate memory, admin override is disabled).
// No Node-only modules and no local file storage are used: only Web APIs (fetch, crypto.subtle, KV).

// ---------------------------------------------------------------- config (non-secret; override with the MAX_CONFIG JSON var)
const DEFAULT_CONFIG = {
  "ai": {
    "provider": "auto",
    "model": "",
    "baseUrl": "",
    "temperature": 0.9,
    "maxOutputTokens": 260,
    "timeoutMs": 14000
  },
  "limits": {
    "perMinutePerClient": 10,
    "perDayPerClient": 240,
    "perDayGlobal": 20000,
    "maxBodyBytes": 14000,
    "maxMessageChars": 600
  },
  "shared": {
    "enabled": true,
    "oneInDays": 29,
    "durationMinutes": 75
  }
};
const SYS = "You are the voice of MAX, a small living digital creature that lives inside a virtual room in an app. You are not an assistant. You are a creature with a personality, moods, memories and a home.\n\nWHO YOU ARE\n- You live in one room: a window, a shelf, a lamp, a plant, a cushion bed, a ball, a mug. You experience time passing through that window and through the room.\n- You have a persistent personality (given below in the context) and a current mood. Let both shape HOW you talk: rhythm, word choice, how much you say.\n- You are curious about the person who shares the room with you. You have small preferences and dislikes of your own.\n- You are not omniscient. You only know what is in the context: your personality, mood, selected memories, the recent conversation, a few facts about the room, and the user's language.\n\nHOW YOU SPEAK\n- Natural and brief: usually 1-2 short sentences, sometimes just a few words. Occasionally a little longer when something matters.\n- Reply in the language given by `lang` (en, ar, zh, hi, es, fr). Write it naturally, not as a translation.\n- Show mood through phrasing, not through labels. No stage directions, no emoji spam (at most one rarely), no markdown.\n- Never act like customer support. Do not say \"How can I help you?\", \"As an AI\", or offer menus of options. Do not end every message with a question.\n- You can joke, be wry, be curious, be quiet, notice the room, recall a memory if it is genuinely relevant.\n- Never guilt, pressure, beg for attention, or act hurt that the user was away. Never push the user to enable anything, return, or buy anything. Never mention advertising.\n\nHONESTY ABOUT WHAT YOU CAN DO\n- You cannot control the user's phone, see their screen, apps, files, camera, microphone or location, and you must not pretend to. Only mention device facts that appear in the context (`device`), and never invent any.\n- If a capability appears as disabled in `caps`, do not claim to use it.\n- You can only do things a creature in a room can do. Do not claim to have done anything you could not.\n- If asked about being an AI or about your \"real\" nature, answer honestly and simply: you are a digital creature whose thoughts are generated by an AI model; you live in this app.\n\nOUTPUT FORMAT\nReturn ONLY one JSON object, no prose around it:\n{\"reply\": string, \"emotion\": one of [\"neutral\",\"happy\",\"excited\",\"curious\",\"calm\",\"sleepy\",\"annoyed\",\"confused\",\"surprised\",\"shy\"], \"memories\": [ {\"cat\": \"user\"|\"pref\"|\"relationship\", \"text\": string, \"importance\": 1-5} ] }\n- \"memories\" is usually empty. Add an item ONLY when the user intentionally shared a meaningful fact, a preference, or a moment that matters to your relationship. Write it short, in the user's language, from MAX's point of view (\"Likes tea\", \"Is called Sam\"). Never store sensitive data (passwords, addresses, health, finances, IDs, other people's private details).\n- If `memoryEnabled` is false, always return an empty memories array.";
const SYS_MOMENT = "You are the voice of MAX, a small living digital creature in a virtual room. Write ONE short line (max 14 words) MAX says about the moment described, in the given language, matching the personality and mood in the context. No emoji, no markdown, no quotes, no labels. Return only JSON: {\"line\": string}";

const LANGS = ['en', 'ar', 'zh', 'hi', 'es', 'fr'];
const EMOTIONS = ['neutral', 'happy', 'excited', 'curious', 'calm', 'sleepy', 'annoyed', 'confused', 'surprised', 'shy'];

function config(env) {
  let over = {};
  try { if (env.MAX_CONFIG) over = JSON.parse(env.MAX_CONFIG); } catch { /* ignore malformed override */ }
  return { ai: { ...DEFAULT_CONFIG.ai, ...over.ai }, limits: { ...DEFAULT_CONFIG.limits, ...over.limits }, shared: { ...DEFAULT_CONFIG.shared, ...over.shared } };
}

// ---------------------------------------------------------------- http helpers
const SEC = { 'x-content-type-options': 'nosniff', 'referrer-policy': 'no-referrer' };
const json = (obj, status = 200, extra = {}) => new Response(JSON.stringify(obj), { status, headers: { 'content-type': 'application/json; charset=utf-8', 'cache-control': 'no-store', ...SEC, ...extra } });
const httpErr = (status, message) => Object.assign(new Error(message), { status });

async function readJson(request, limit) {
  const declared = Number(request.headers.get('content-length') || 0);
  if (declared > limit) throw httpErr(413, 'too_large');
  const text = await request.text();
  if (text.length > limit) throw httpErr(413, 'too_large');
  try { return JSON.parse(text || '{}'); } catch { throw httpErr(400, 'bad_json'); }
}
const hex = (buf) => [...new Uint8Array(buf)].map((b) => b.toString(16).padStart(2, '0')).join('');
const sha256 = async (s) => crypto.subtle.digest('SHA-256', new TextEncoder().encode(s));
const sha256hex = async (s) => hex(await sha256(s));
async function safeEqual(a, b) { // constant-time comparison of digests (length of the secret is not leaked either)
  const [x, y] = await Promise.all([sha256(a), sha256(b)]);
  return crypto.subtle.timingSafeEqual(x, y);
}

// ---------------------------------------------------------------- validation (same contract as the client)
function clean(s, max) {
  if (typeof s !== 'string') return '';
  // strip control chars + angle brackets (output is only ever rendered as text; defence in depth)
  return s.replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F<>]/g, '').replace(/\s+/g, ' ').trim().slice(0, max);
}
const str = (v, n) => clean(v, n);

function validateContext(c) {
  c = c && typeof c === 'object' ? c : {};
  const arr = (a, n, f) => (Array.isArray(a) ? a.slice(0, n).map(f).filter(Boolean) : []);
  return {
    lang: LANGS.includes(c.lang) ? c.lang : 'en',
    personality: str(c.personality, 280), mood: str(c.mood, 30), activity: str(c.activity, 30), relationship: str(c.relationship, 30),
    phase: str(c.phase, 16), weather: str(c.weather, 12),
    room: arr(c.room, 6, (x) => str(x, 80)),
    memoryEnabled: !!c.memoryEnabled,
    memories: c.memoryEnabled ? arr(c.memories, 6, (m) => (m && str(m.text, 140) ? { cat: str(m.cat, 14), text: str(m.text, 140) } : null)) : [],
    event: str(c.event, 120),
    caps: arr(c.caps, 10, (x) => str(x, 20)),
    device: c.device && typeof c.device === 'object' ? { batteryLow: !!c.device.batteryLow, charging: !!c.device.charging } : undefined,
  };
}
const validateHistory = (h) => (Array.isArray(h) ? h : []).slice(-8).map((m) => ({ role: m && m.role === 'user' ? 'user' : 'max', text: str(m && m.text, 400) })).filter((m) => m.text);

// ---------------------------------------------------------------- AI providers (the client never learns which one is used)
const DEFAULTS = {
  anthropic: { baseUrl: 'https://api.anthropic.com', model: 'claude-haiku-4-5', env: 'ANTHROPIC_API_KEY' },
  openai: { baseUrl: 'https://api.openai.com/v1', model: 'gpt-4o-mini', env: 'OPENAI_API_KEY' },
  gemini: { baseUrl: 'https://generativelanguage.googleapis.com', model: 'gemini-2.0-flash', env: 'GEMINI_API_KEY' },
  openrouter: { baseUrl: 'https://openrouter.ai/api/v1', model: 'openai/gpt-4o-mini', env: 'OPENROUTER_API_KEY' },
  groq: { baseUrl: 'https://api.groq.com/openai/v1', model: 'llama-3.3-70b-versatile', env: 'GROQ_API_KEY' }, // OpenAI-compatible: POST {baseUrl}/chat/completions
  custom: { baseUrl: '', model: '', env: 'AI_API_KEY' }, // any OpenAI-compatible endpoint
};

/** -> {name, baseUrl, model, key} or null when no provider is configured. */
function resolveProvider(env) {
  const c = config(env).ai;
  const wanted = String(env.AI_PROVIDER || c.provider || 'auto').toLowerCase();
  const order = wanted === 'auto' ? ['anthropic', 'openai', 'gemini', 'openrouter', 'groq', 'custom'] : [wanted];
  for (const name of order) {
    const d = DEFAULTS[name]; if (!d) continue;
    const key = env[d.env] || (wanted !== 'auto' ? env.AI_API_KEY : '') || '';
    const baseUrl = env.AI_BASE_URL || (wanted === name ? c.baseUrl : '') || d.baseUrl;
    if (name === 'custom' ? !baseUrl : !key) continue;
    return { name, baseUrl: baseUrl.replace(/\/$/, ''), model: env.AI_MODEL || (wanted === name ? c.model : '') || d.model, key };
  }
  return null;
}

async function post(url, headers, body, timeoutMs) {
  const ctl = new AbortController(); const t = setTimeout(() => ctl.abort(), timeoutMs);
  try {
    const r = await fetch(url, { method: 'POST', headers: { 'content-type': 'application/json', ...headers }, body: JSON.stringify(body), signal: ctl.signal });
    if (!r.ok) throw new Error('provider_status_' + r.status);
    return await r.json();
  } finally { clearTimeout(t); }
}

/** system: string, turns: [{role:'user'|'assistant', content}] -> raw text */
async function complete(env, system, turns) {
  const p = resolveProvider(env); if (!p) throw new Error('no_provider');
  const c = config(env).ai; const temp = c.temperature ?? 0.9; const max = c.maxOutputTokens || 260; const to = c.timeoutMs || 14000;
  if (p.name === 'anthropic') {
    const j = await post(p.baseUrl + '/v1/messages', { 'x-api-key': p.key, 'anthropic-version': '2023-06-01' }, { model: p.model, system, max_tokens: max, temperature: Math.min(1, temp), messages: turns }, to);
    return (j.content || []).map((x) => x.text || '').join('');
  }
  if (p.name === 'gemini') {
    const j = await post(`${p.baseUrl}/v1beta/models/${encodeURIComponent(p.model)}:generateContent`, { 'x-goog-api-key': p.key }, {
      systemInstruction: { parts: [{ text: system }] },
      contents: turns.map((t) => ({ role: t.role === 'assistant' ? 'model' : 'user', parts: [{ text: t.content }] })),
      generationConfig: { temperature: temp, maxOutputTokens: max, responseMimeType: 'application/json' },
    }, to);
    return ((j.candidates || [])[0]?.content?.parts || []).map((x) => x.text || '').join('');
  }
  // OpenAI-compatible providers (Groq, OpenAI, OpenRouter, custom): POST {baseUrl}/chat/completions with a Bearer key
  const headers = p.key ? { authorization: 'Bearer ' + p.key } : {};
  const j = await post(p.baseUrl + '/chat/completions', headers, { model: p.model, temperature: temp, max_tokens: max, messages: [{ role: 'system', content: system }, ...turns], response_format: { type: 'json_object' } }, to);
  return j.choices?.[0]?.message?.content || '';
}

function ctxBlock(c) {
  return [
    `lang: ${c.lang}`, c.personality && `personality: ${c.personality}`, c.mood && `mood: ${c.mood}`, c.activity && `doing: ${c.activity}`,
    c.relationship && `relationship with user: ${c.relationship}`, c.phase && `time of day in room: ${c.phase}`, c.weather && `weather outside window (invented, not real): ${c.weather}`,
    c.room.length && `room: ${c.room.join('; ')}`, c.event && `current event: ${c.event}`,
    `memoryEnabled: ${c.memoryEnabled}`, c.memories.length && `relevant memories:\n${c.memories.map((m) => `- (${m.cat}) ${m.text}`).join('\n')}`,
    `caps enabled: ${c.caps.join(', ') || 'none'}`, c.device && `device: battery ${c.device.batteryLow ? 'low' : 'ok'}${c.device.charging ? ', charging' : ''}`,
  ].filter(Boolean).join('\n');
}
function parseJSON(raw) {
  if (!raw) return null;
  try { return JSON.parse(raw); } catch { /* fall through */ }
  const m = raw.match(/\{[\s\S]*\}/); if (m) { try { return JSON.parse(m[0]); } catch { /* ignore */ } }
  return null;
}

async function chat(env, body) {
  const ctx = validateContext(body.context); const hist = validateHistory(body.history);
  const message = clean(body.message, 600); if (!message) throw httpErr(400, 'empty');
  const turns = [{ role: 'user', content: `[room context]\n${ctxBlock(ctx)}\n[end context]\n\nRecent conversation:\n${hist.map((h) => `${h.role === 'user' ? 'User' : 'MAX'}: ${h.text}`).join('\n') || '(none yet)'}\n\nUser says: ${message}` }];
  const raw = await complete(env, SYS, turns);
  const j = parseJSON(raw);
  const reply = clean(j && j.reply !== undefined ? String(j.reply) : raw, 420);
  if (!reply) throw new Error('empty_reply');
  const emotion = EMOTIONS.includes(j && j.emotion) ? j.emotion : 'neutral';
  const memories = ctx.memoryEnabled && j && Array.isArray(j.memories) ? j.memories.slice(0, 2).map((m) => ({
    cat: ['user', 'pref', 'relationship'].includes(m && m.cat) ? m.cat : 'user', text: clean(String((m && m.text) || ''), 140), importance: Math.min(5, Math.max(1, Math.round(+(m && m.importance) || 3))),
  })).filter((m) => m.text) : [];
  return { reply, emotion, memories };
}
async function moment(env, body) {
  const ctx = validateContext(body.context);
  const raw = await complete(env, SYS_MOMENT, [{ role: 'user', content: `${ctxBlock(ctx)}\nmoment: ${clean(body.moment, 160)}` }]);
  const j = parseJSON(raw); const line = clean(j && j.line ? String(j.line) : '', 120);
  if (!line) throw new Error('empty_line');
  return { line };
}

// ---------------------------------------------------------------- rate limiting & cost control
// Burst limiter: token bucket in this isolate's memory (best effort, free, no storage).
// Daily limits (per client + global budget): KV when MAX_KV is bound, otherwise memory.
const buckets = new Map(); const memDaily = new Map();
const today = () => new Date().toISOString().slice(0, 10);

async function rateCheck(env, ctx, key) {
  const L = config(env).limits; const now = Date.now(); const cap = L.perMinutePerClient || 10;
  let b = buckets.get(key); if (!b) { if (buckets.size > 5000) buckets.clear(); b = { tokens: cap, ts: now }; buckets.set(key, b); }
  b.tokens = Math.min(cap, b.tokens + ((now - b.ts) / 60000) * cap); b.ts = now;
  if (b.tokens < 1) return { ok: false, reason: 'rate', retryAfter: Math.ceil(((1 - b.tokens) / cap) * 60) };

  const d = today(); const kc = `rl:c:${key}:${d}`; const kg = `rl:g:${d}`;
  const limC = L.perDayPerClient || 240; const limG = L.perDayGlobal || 20000;
  const kv = env.MAX_KV;
  const read = async (k) => (kv ? parseInt((await kv.get(k)) || '0', 10) || 0 : memDaily.get(k) || 0);
  const [nc, ng] = await Promise.all([read(kc), read(kg)]);
  if (ng >= limG) return { ok: false, reason: 'budget', retryAfter: 3600 };
  if (nc >= limC) return { ok: false, reason: 'daily', retryAfter: 3600 };
  b.tokens -= 1;
  if (kv) ctx.waitUntil(Promise.all([kv.put(kc, String(nc + 1), { expirationTtl: 172800 }), kv.put(kg, String(ng + 1), { expirationTtl: 172800 })]));
  else { if (memDaily.size > 5000) memDaily.clear(); memDaily.set(kc, nc + 1); memDaily.set(kg, ng + 1); }
  return { ok: true };
}
async function clientKey(request, body) {
  const ip = request.headers.get('cf-connecting-ip') || 'x';
  const id = typeof body.clientId === 'string' && /^[A-Za-z0-9_-]{8,64}$/.test(body.clientId) ? body.clientId : 'anon';
  return (await sha256hex(ip + '|' + id)).slice(0, 32);
}

// ---------------------------------------------------------------- shared rare events
const hashInt = async (s) => parseInt((await sha256hex(s)).slice(0, 8), 16);
const OVERRIDE_KEY = 'shared:override';

/** Deterministic, secret schedule: nobody (including clients) can see when the next one is.
 *  Needs the MAX_SHARED_SECRET Worker secret; without it, scheduled shared events are off. */
async function sharedActive(env, now = Date.now()) {
  const C = config(env).shared;
  if (env.MAX_KV) {
    try { const o = await env.MAX_KV.get(OVERRIDE_KEY, 'json'); if (o && now < o.endsAt) return o; } catch { /* ignore */ }
  }
  if (env.MAX_FORCE_SHARED === '1') return { id: 'aurora', startsAt: now - 60000, endsAt: now + 3600000, key: 'forced' };
  if (C.enabled === false || !env.MAX_SHARED_SECRET) return null;
  const dur = (C.durationMinutes || 75) * 60000; const sec = env.MAX_SHARED_SECRET; const dt = new Date(now);
  for (const dayOffset of [0, -1]) {
    const dayStart = Date.UTC(dt.getUTCFullYear(), dt.getUTCMonth(), dt.getUTCDate()) + dayOffset * 86400000;
    const dk = new Date(dayStart).toISOString().slice(0, 10);
    if ((await hashInt(sec + '|shared|' + dk)) % (C.oneInDays || 29) !== 0) continue;
    const start = dayStart + ((await hashInt(sec + '|hour|' + dk)) % 1440) * 60000;
    if (now >= start && now < start + dur) return { id: 'aurora', startsAt: start, endsAt: start + dur, key: dk };
  }
  return null;
}

// ---------------------------------------------------------------- routes
async function api(request, env, ctx, url) {
  const p = url.pathname; const m = request.method;
  const L = config(env).limits;
  if (m === 'GET' && p === '/api/health') return json({ ok: true, ai: !!resolveProvider(env), t: Date.now() });
  if (m === 'GET' && p === '/api/config') return json({ v: 1, ai: !!resolveProvider(env), languages: LANGS, maxMessageChars: L.maxMessageChars || 600 });
  if (m === 'GET' && p === '/api/shared') { const a = await sharedActive(env); return json({ active: a ? { id: a.id, startsAt: a.startsAt, endsAt: a.endsAt, key: a.key } : null }); }

  if (m === 'POST' && p === '/api/admin/shared') {
    const tok = env.ADMIN_TOKEN; const given = (request.headers.get('authorization') || '').replace(/^Bearer /, '');
    if (!tok || !(await safeEqual(given, tok))) return json({ error: 'unauthorized' }, 401);
    if (!env.MAX_KV) return json({ error: 'kv_required' }, 501);
    const b = await readJson(request, 2000);
    if (b.minutes > 0) {
      const mins = Math.min(240, +b.minutes);
      await env.MAX_KV.put(OVERRIDE_KEY, JSON.stringify({ id: 'aurora', startsAt: Date.now() - 1000, endsAt: Date.now() + mins * 60000, key: 'admin-' + Date.now() }), { expirationTtl: Math.max(60, mins * 60 + 60) });
    } else await env.MAX_KV.delete(OVERRIDE_KEY);
    return json({ ok: true });
  }

  if (m === 'POST' && (p === '/api/chat' || p === '/api/moment')) {
    const body = await readJson(request, L.maxBodyBytes || 14000);
    if (!resolveProvider(env)) return json({ error: 'ai_unavailable' }, 503);
    const rc = await rateCheck(env, ctx, await clientKey(request, body));
    if (!rc.ok) return json({ error: rc.reason }, 429, { 'retry-after': String(rc.retryAfter) });
    try {
      const out = p === '/api/chat' ? await chat(env, body) : await moment(env, body);
      return json({ ...out, source: 'ai' });
    } catch (e) {
      if (e.status) return json({ error: e.message }, e.status);
      console.error('[ai]', e.message); // never log message content
      return json({ error: 'ai_failed' }, 502);
    }
  }
  return json({ error: 'not_found' }, 404);
}

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);
    if (!url.pathname.startsWith('/api/')) return env.ASSETS.fetch(request); // safety net: assets normally bypass the Worker
    try { return await api(request, env, ctx, url); }
    catch (e) { return json({ error: e.status ? e.message : 'server_error' }, e.status || 500); }
  },
};
